### ISSUE TITLE
Tag Nameplates not working

### ISSUE THREAD

**Issue by H3wastooshort** [Fewdys/FewTags-CVR#4]
The fewtag nameplates show up as blank user nameplates on the latest stable CVR release 2024r174 in desktop mode:

![yen](https://github.com/Fewdys/FewTags-CVR/assets/29732082/1e38d4d3-a5bb-4b80-abb5-62291811fd22)

**Comment by Fewdys** [comment]
I'll look into it within the next 2 days, thx for letting me know

**Comment by Fewdys** [comment]
Cant seem to recreate the Issue with it not properly creating the Plate, however there were Other Issues in which I have just decided to remove Plates itself & Instead just display text for tags as seen below. with that being said an update can be found in releases, If you continue to have issues please do let me know by creating a new issue. Also be sure to make sure other mods aren't interfering.
![image](https://github.com/Fewdys/FewTags-CVR/assets/104469110/843e8618-5a8c-4d9f-8e9f-17d5a9bd5128)
